# Disable sandboxing options globally that will not work in a container environment
[Service]
ProcSubset=all
ProtectProc=default
ProtectControlGroups=no
ProtectKernelTunables=no
NoNewPrivileges=no
ProtectKernelLogs=no
ProtectKernelModules=no
PrivateTmp=no
PrivateDevices=no
ProtectHome=no
ProtectSystem=no
RestrictNamespaces=no
LockPersonality=no
RestrictRealtime=no
ReadWritePaths=
ReadOnlyPaths=
ImportCredential=