# Default configuration

# - General configuration -
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"
metadata_fsync = true
data_fsync = true
replication_factor = 1

# - RPC configuration -
rpc_bind_addr = "[::]:3901"

# - S3 API configuration -
[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"