inputs.conntrack
inputs.cpu
inputs.disk
inputs.diskio
inputs.docker
inputs.elasticsearch
inputs.http
inputs.interrupts
inputs.kernel
inputs.kernel_vmstat
inputs.mem
inputs.mongodb
inputs.mysql
inputs.net
inputs.netstat
inputs.nfsclient
inputs.pgbouncer
inputs.postgresql
inputs.processes
inputs.prometheus
inputs.redis
inputs.sensors
inputs.swap
inputs.system
outputs.discard
outputs.file
outputs.http
outputs.kafka
outputs.opentelemetry
outputs.postgresql
outputs.prometheus_client
processors.regex
processors.rename
processors.round