---
name: Build Actual Budget image
on:
  push:
    branches:
      - main
    paths:
      - 'actual-budget/**'
      - '!actual-budget/README.md'
      - '.github/workflows/build-actual.yml'
  workflow_dispatch:
  schedule:
    - cron: '35 4 * * 6' # Every Saturday at 04:35am
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: ['24.6.0']
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to registry
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: ./actual-budget
          file: ./actual-budget/Dockerfile
          push: true
          build-args: |
            VERSION=${{ matrix.version }}
          tags: |
            ghcr.io/f-bn/actual-budget:${{ matrix.version }}
            ghcr.io/f-bn/actual-budget:latest