---
name: Build AdGuard Home image
on:
  push:
    branches:
      - main
    paths:
      - adguard-home/**
      - .github/workflows/build-adguard.yml
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: ['0.107.48']
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to registry
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: ./adguard-home
          file: ./adguard-home/Dockerfile
          push: true
          build-args: |
            VERSION=${{ matrix.version }}
          tags: |
            ghcr.io/f-bn/adguard-home:${{ matrix.version }}