---
name: Build Watchtower image
env:
  build_epoch: 1
on:
  push:
    branches:
      - main
    paths:
      - 'watchtower/**'
      - '!watchtower/README.md'
      - '.github/workflows/build-watchtower.yml'
  workflow_dispatch:
  schedule:
    - cron: '35 4 * * 6' # Every Saturday at 04:35am
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: ['1.7.1']
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to registry
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: ./watchtower
          file: ./watchtower/Dockerfile
          push: true
          build-args: |
            PG_RELEASE=${{ matrix.version }}
          tags: |
            ghcr.io/f-bn/watchtower:${{ matrix.version }}-r${{ env.build_epoch }}
            ghcr.io/f-bn/watchtower:${{ matrix.version }}
            ghcr.io/f-bn/watchtower:latest