---
name: Build MinIO image
on:
  push:
    branches:
      - main
    paths:
      - 'minio/**'
      - '!minio/README.md'
      - '.github/workflows/build-minio.yml'
  workflow_dispatch:
  schedule:
    - cron: '35 4 * * 6' # Every Saturday at 04:35am
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        minio_version: ['RELEASE.2025-01-20T14-49-07Z']
        mc_version: ['RELEASE.2025-01-17T23-25-50Z']
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch build)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to registry
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: ./minio
          file: ./minio/Dockerfile
          push: true
          build-args: |
            MINIO_VERSION=${{ matrix.minio_version }}
            MC_VERSION=${{ matrix.mc_version }}
          tags: |
            ghcr.io/f-bn/minio:${{ matrix.minio_version }}
            ghcr.io/f-bn/minio:latest