---
name: Build Ubuntu Toolbox image
on:
  push:
    branches:
      - main
    paths:
      - 'ubuntu-toolbox/**/**'
      - '!ubuntu-toolbox/README.md'
      - '.github/workflows/build-ubuntu-toolbox.yml'
  workflow_dispatch:
  schedule:
    - cron: '35 4 * * 6' # Every Saturday at 04:35am
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: ['25.04', '24.04']
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to registry
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: ./ubuntu-toolbox/${{ matrix.version }}
          file: ./ubuntu-toolbox/${{ matrix.version }}/Dockerfile
          push: true
          tags: |
            ghcr.io/f-bn/ubuntu-toolbox:${{ matrix.version }}
