---
name: Cleanup old container images versions
on:
 workflow_dispatch:
 schedule:
   - cron: '00 4 * * 6' # Every Saturday at 04:00am
jobs:
 cleanup:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write
   strategy:
     matrix:
       package: ['adguard-home','distrobuilder','ferretdb','minio','navidrome','pgbouncer','postgresql','valkey','watchtower']
   steps:
    - uses: snok/container-retention-policy@v3.0.0
      with:
        account: user
        token: ${{ secrets.GITHUB_TOKEN }}
        image-names: "${{ matrix.package }}"
        tag-selection: both
        cut-off: 4w
        rust-log: container_retention_policy=debug